export { default as AwardCheck } from './award-check';
export { default as BookSearch } from './book-search';
export { default as BrainGear } from './brain-gear';
export { default as Flashcards } from './flashcards';
export { default as GraduationCap } from './graduation-cap';
export { default as LikeStar } from './like-star';
export { default as UsersSpeech } from './users-speech';
export { default as VibrateHeadphone } from './vibrate-headphone';
export { default as Zalo } from './zalo';
