import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';
import clsx from 'clsx';

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin', 'vietnamese'],
});

export const metadata: Metadata = {
  title: 'HSK Phúc - Luyện thi HSK cùng thầy Phúc',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="vi" className={clsx('mdl-js', nunito.variable)}>
      <body cz-shortcut-listen="true">
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
